services:
  wdio:
    image: wdio-cucumber_3:latest
    user: root  # Gunakan root untuk memastikan izin file
    volumes:
      - ./jenkins_workspace:/app
      - /app/node_modules
      - .:/app
      - ./allure-results:/app/allure-results
      - ~/.npm:/root/.npm  # Cache npm di direktori lokal
    environment:
      - DISPLAY=:99
      - FEATURE_TAG=${FEATURE_TAG}
    command: >
      sh -c "cp -r /tmp/initial-files/* /app &&
      npm install &&
      Xvfb :99 -screen 0 1280x1024x24 & sleep 2 &&
      npx wdio run wdio.conf.js --cucumberOpts.tags='${FEATURE_TAG}'"
    working_dir: /app
