services:
  wdio:
    image: wdio-cucumber_2:latest
    user: root  # Temporarily using root for container initialization
    volumes:
      - C:/ProgramData/Jenkins/.jenkins/workspace/docker-wdio-3:/app
      - C:/ProgramData/Jenkins/.jenkins/workspace/docker-wdio-3/allure-results:/app/allure-results
    environment:
      - DISPLAY=:99
      - TAG=${FEATURE_TAG}
    command: "sh -c 'Xvfb :99 -screen 0 1280x1024x24 & npx wdio run wdio.conf.js --cucumberOpts.tagExpression ${FEATURE_TAG}'"
    working_dir: /app
