version: '3'
services:
  wdio:
    image: wdio-cucumber:latest
    user: root  # Use root during setup and initialization
    volumes:
      - .:/app
      - ./allure-results:/app/allure-results
    environment:
      - DISPLAY=:99
      - FEATURE_TAG=${FEATURE_TAG}
    command: >
      sh -c "Xvfb :99 -screen 0 1280x1024x24 & 
      npx wdio run wdio.conf.js --cucumberOpts.tagExpression='${FEATURE_TAG}'"
    working_dir: /app
