services:
  wdio:
    image: wdio-cucumber_master:latest
    user: root
    volumes:
      - ./jenkins_workspace:/app
      - /app/node_modules
      - .:/app
      - ./allure-results:/app/allure-results
      - ~/.npm:/root/.npm
    environment:
      - DISPLAY=:99
      - FEATURE_TAG=${FEATURE_TAG:-@HotelFeature} # Default value if not set
    working_dir: /app
    command: >
      sh -c "
      cp -r /tmp/initial-files/* /app &&
      npm install &&
      Xvfb :99 -screen 0 1280x1024x24 & sleep 2 &&
      npx wdio run wdio.conf.js --cucumberOpts.tags='${FEATURE_TAG}' &&
      allure generate /app/allure-results --clean -o /app/allure-report
      "