services:
  wdio:
    image: wdio-cucumber  # Use the pre-built image
    container_name: wdio-cucumber
    volumes:
      - .:/app
      - ./reports:/app/allure-results # Mount reports directory
    working_dir: /app