services:
  wdio:
    build:
      context: ..
      dockerfile: ./docker/dockerfile-wdio
    container_name: wdio-tests
    networks:
      - docker_default  # Connect to the same network as Selenium Grid
    environment:
      - WDIO_BASE_URL=http://selenium-hub:4444
      - CUCUMBER_TAGS=${CUCUMBER_TAGS}
    volumes:
      - ..:/app
    working_dir: /app
    command: ["sh", "-c", "ls -l /app && npx wdio /app/wdio.conf.ts"]

networks:
  docker_default:
    external: true  # Use the same network as Selenium Grid
